server:
  port: 8083
spring:
  application:
    name: buy
  cloud:
    consul:
      host: localhost
      port: 8500

  datasource:
    username: pg3402
    url: jdbc:postgresql://localhost:5432/users
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
