server:
  port: 8081

spring:
  application:
    name: users

  datasource:
    username: pg3402
    url: jdbc:postgresql://localhost:5432/users
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
