server:
  port: 8082
spring:
  application:
    name: cheater
  datasource:
    username: pg3402
    url: jdbc:postgresql://localhost:5432/cheaters
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true